# =============================================================================
# sparse-both.yml – Both sparseCheckoutDirectories AND sparseCheckoutPatterns
# =============================================================================
# PURPOSE: Determine which property takes precedence when BOTH are set.
#
# DOCUMENTATION CLAIM:
#   "If both sparseCheckoutDirectories and sparseCheckoutPatterns are specified,
#    sparseCheckoutPatterns is used and sparseCheckoutDirectories is ignored."
#
# ⚠️  ACTUAL BEHAVIOUR OBSERVED – Build 712 (agent v4.266.2 / git 2.43.0):
#   sparseCheckoutDirectories WON – cone mode was used, patterns were IGNORED.
#   PRESENT  : FolderA/a1.txt  RootFile1.yml  RootFile2.yml  (cone mode + FolderA)
#   ABSENT   : CDN/cdnfile1.txt  CDN/nested/cdnfile2.txt
#
# CONTRAST – documented (patterns win) vs. observed (dirs win):
#   documented (patterns win)   → CDN PRESENT,    FolderA ABSENT, root files ABSENT
#   actual observed (dirs win)  → FolderA PRESENT, CDN ABSENT,    root files PRESENT
#
# Build 712 raw git commands logged by agent:
#   ##[command]git sparse-checkout init --cone
#   ##[command]git sparse-checkout set FolderA tools
#   (CDN/** pattern was never passed to git)
#
# If FolderA/a1.txt is PRESENT in the pipeline logs, directories won. ✓ (Build 712)
# =============================================================================

name: "SparseDemo_SparseBoth_$(Build.BuildId)"

trigger: none
pr: none

variables:
  - name: agentPoolName
    value: "Default" # ← Change to your self-hosted pool name
  - name: evidenceLabel
    value: "SPARSE-BOTH-PATTERNS-WIN"

pool:
  name: $(agentPoolName)

jobs:
  - job: SparseBoth
    displayName: "Sparse Checkout – Both set (⚠️ dirs won on v4.266.2)"
    workspace:
      clean: all
    steps:
      # -----------------------------------------------------------------------
      # 1. Checkout – BOTH properties set
      #    sparseCheckoutDirectories is intentionally set to a different value
      #    (FolderA) so that if it were used, FolderA would appear.
      #    sparseCheckoutPatterns targets CDN/** so only CDN should appear.
      #    The ABSENCE of FolderA proves patterns won.
      # -----------------------------------------------------------------------
      - checkout: self
        clean: true
        persistCredentials: true
        # DIRECTORIES (cone mode) – intentionally set to FolderA (+tools so
        # the inspection script is available whichever mode wins).
        # The KEY evidence is whether FolderA or CDN ends up in the workspace.
        sparseCheckoutDirectories: FolderA tools
        # PATTERNS (non-cone mode) – this is what should actually be used.
        # Only CDN/** is matched; FolderA and root files should be absent.
        sparseCheckoutPatterns: |
          CDN/**
          tools/**
        displayName: "Checkout (BOTH: directories=FolderA, patterns=CDN/** tools/** → ⚠️ dirs won on Build 712)"

      # -----------------------------------------------------------------------
      # 2. Environment banner
      # -----------------------------------------------------------------------
      - script: |
          echo "##[section]====== AGENT & ENVIRONMENT INFO ======"
          echo "Pipeline:              $(Build.DefinitionName)"
          echo "Evidence Label:        $(evidenceLabel)"
          echo "Build ID:              $(Build.BuildId)"
          echo "Agent Name:            $(Agent.Name)"
          echo "Agent OS:              $(Agent.OS)"
          echo "Agent Version:         $(Agent.Version)"
          echo "Sources Dir:           $(Build.SourcesDirectory)"
          echo "Sparse Mode:           BOTH SET – ⚠️ see docs for discrepancy finding"
          echo "sparseCheckoutDirs:    FolderA tools  (WON on Build 712 – agent v4.266.2)"
          echo "sparseCheckoutPatterns: CDN/** tools/**  (IGNORED on Build 712 – agent v4.266.2)"
          echo ""
          echo "##[section]====== PROOF LOGIC ======"
          echo "  If FolderA/a1.txt is PRESENT → directories won (observed on Build 712)"
          echo "  If FolderA/a1.txt is ABSENT  → patterns won (documented behaviour)"
          echo "  If RootFile1.yml   is PRESENT → cone mode was used (observed on Build 712)"
          echo "  If RootFile1.yml   is ABSENT  → pattern mode was used (documented behaviour)"
          git --version
          echo "##[section]====== GIT SPARSE-CHECKOUT STATUS ======"
          cd "$(Build.SourcesDirectory)"
          git sparse-checkout list || echo "(sparse-checkout list not available)"
        displayName: "Print agent and environment info"
        continueOnError: true

      # -----------------------------------------------------------------------
      # 3. Workspace inspection – cross-platform
      # -----------------------------------------------------------------------
      - powershell: |
          $env:SPARSE_MODE = "$(evidenceLabel)"
          $env:SOURCES_DIR = "$(Build.SourcesDirectory)"
          & "$(Build.SourcesDirectory)/tools/inspect-workspace.ps1"
        displayName: "Inspect workspace (PowerShell)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')
        continueOnError: true

      - bash: |
          export SPARSE_MODE="$(evidenceLabel)"
          export SOURCES_DIR="$(Build.SourcesDirectory)"
          bash "$(Build.SourcesDirectory)/tools/inspect-workspace.sh"
        displayName: "Inspect workspace (Bash)"
        condition: ne(variables['Agent.OS'], 'Windows_NT')
        continueOnError: true
